# Form implementation generated from reading ui file 'PixelBattle.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QApplication, QMainWindow, QPushButton, QGridLayout, QWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 681, 451))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_grid = QtWidgets.QGridLayout()
        self.left_grid.setObjectName("left_grid")
        self.name_line = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_line.sizePolicy().hasHeightForWidth())
        self.name_line.setSizePolicy(sizePolicy)
        self.name_line.setObjectName("name_line")
        self.left_grid.addWidget(self.name_line, 0, 1, 1, 2)
        self.room = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.room.sizePolicy().hasHeightForWidth())
        self.room.setSizePolicy(sizePolicy)
        self.room.setObjectName("room")
        self.left_grid.addWidget(self.room, 1, 0, 1, 1)
        self.connect_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.connect_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_btn.sizePolicy().hasHeightForWidth())
        self.connect_btn.setSizePolicy(sizePolicy)
        self.connect_btn.setObjectName("connect_btn")
        self.left_grid.addWidget(self.connect_btn, 0, 3, 1, 1)
        self.name = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setObjectName("name")
        self.left_grid.addWidget(self.name, 0, 0, 1, 1)
        self.chat = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.chat.setObjectName("chat")
        self.left_grid.addWidget(self.chat, 2, 0, 1, 1)
        self.send_msg_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.send_msg_btn.setObjectName("send_msg_btn")
        self.left_grid.addWidget(self.send_msg_btn, 4, 2, 1, 2)
        self.chat_line = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_line.sizePolicy().hasHeightForWidth())
        self.chat_line.setSizePolicy(sizePolicy)
        self.chat_line.setObjectName("chat_line")
        self.left_grid.addWidget(self.chat_line, 4, 0, 1, 2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)


        self.lobby_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.lobby_btn.setObjectName("lobby_btn")
        self.left_grid.addWidget(self.lobby_btn, 1, 1, 1, 1)
        self.room2_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.room2_btn.setObjectName("room2_btn")
        self.left_grid.addWidget(self.room2_btn, 1, 3, 1, 1)
        self.room1_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.room1_btn.setObjectName("room1_btn")
        self.left_grid.addWidget(self.room1_btn, 1, 2, 1, 1)

        self.chat_field = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget)
        self.chat_field.setMinimumSize(QtCore.QSize(283, 340))
        self.chat_field.setObjectName("chat_field")
        self.left_grid.addWidget(self.chat_field, 3, 0, 1, 4)
        self.chat_field.setReadOnly(True)
        self.horizontalLayout.addLayout(self.left_grid)
        self.right_field = QtWidgets.QVBoxLayout()
        self.right_field.setObjectName("right_field")
        self.upper_side = QtWidgets.QHBoxLayout()
        self.upper_side.setObjectName("upper_side")


        self.game_field = QWidget()
        self.game_field = QtWidgets.QGridLayout()
        self.game_field.setObjectName("game_field")
        self.upper_side.addLayout(self.game_field)

        self.right_field.addLayout(self.upper_side)
        self.lower_side = QtWidgets.QGridLayout()
        self.lower_side.setObjectName("lower_side")
        self.save_pic_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_pic_btn.sizePolicy().hasHeightForWidth())
        self.save_pic_btn.setSizePolicy(sizePolicy)
        self.save_pic_btn.setObjectName("save_pic_btn")
        self.lower_side.addWidget(self.save_pic_btn, 0, 1, 1, 1)
        self.chs_clr_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chs_clr_btn.sizePolicy().hasHeightForWidth())
        self.chs_clr_btn.setSizePolicy(sizePolicy)
        self.chs_clr_btn.setObjectName("chs_clr_btn")
        self.lower_side.addWidget(self.chs_clr_btn, 0, 0, 1, 1)
        self.right_field.addLayout(self.lower_side)
        self.horizontalLayout.addLayout(self.right_field)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.game_field = QWidget()
        self.game_layout = QGridLayout(self.game_field)
        self.game_layout.setSpacing(1)

        # game_field в upper_side
        self.upper_side.addWidget(self.game_field)

        # self.buttons = []
        # self.grid_width = 16  # Ширина сетки
        # self.grid_height = 16  # Высота сетки
        #
        # for y in range(self.grid_height):
        #     row_btns = []
        #     for x in range(self.grid_width):
        #         btn = QPushButton('')
        #         btn.setFixedSize(24, 24)
        #         btn.setStyleSheet("background-color: #FFFFFF; border: 1.1px solid #CCC;")
        #         btn.clicked.connect(self.make_draw_callback(x, y))
        #         self.game_layout.addWidget(btn, y, x)
        #         row_btns.append(btn)
        #     self.buttons.append(row_btns)

        # self.horizontalLayout.addLayout(self.left_grid)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def make_draw_callback(self, x, y):
        def callback():
            print(f"Button clicked at ({x}, {y})")
        return callback

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PixleBattle"))
        self.room.setText(_translate("MainWindow", "Room:"))
        self.connect_btn.setText(_translate("MainWindow", "Rename"))
        self.lobby_btn.setText(_translate("MainWindow", "Lobby"))
        self.room1_btn.setText(_translate("MainWindow", "1"))
        self.room2_btn.setText(_translate("MainWindow", "2"))
        self.name.setText(_translate("MainWindow", "Name:"))
        self.chat.setText(_translate("MainWindow", "Chat"))
        self.send_msg_btn.setText(_translate("MainWindow", "Send message"))
        self.save_pic_btn.setText(_translate("MainWindow", "Save picture"))
        self.chs_clr_btn.setText(_translate("MainWindow", "Choose color"))



if __name__ == "__main__":
    app = QApplication(sys.argv)  # создаем объект приложения
    MainWindow = QtWidgets.QMainWindow()  # создаем главное окно
    ui = Ui_MainWindow()  # создаем объект класса, который отвечает за интерфейс
    ui.setupUi(MainWindow)  # настраиваем интерфейс
    MainWindow.show()  # показываем окно
    sys.exit(app.exec())  # запускаем цикл обработки событий
